/*------------------------------
   SHOWDIB.H : Fichier d'en-tete
  ------------------------------*/

#define IDM_OPEN					10
#define IDM_QUITTER					20
#define IDM_SETDIBITSTODEVICE				30
#define	IDM_STRETCHDIBITS				40
#define IDM_BITBLT_GRANDEUR_REELLE			50
#define IDM_STRETCHBLT_GRANDEUR_FENETRE			60
#define IDM_STRETCHBLT_GRANDEUR_FENETRE_PROPORTIONNEL	70
#define IDM_REGLAGE_COULEURS				80
#define IDD_REDESSINER					90
#define IDM_CHANGEMENT_COULEURS				100
#define IDD_POURCENTAGE					110
#define IDD_SATURATION					120
#define ROUGE						0
#define VERT						1
#define BLEU						2
