# template for "Guess the number" mini-project
# input will come from buttons and an input field
# all output for the game will be printed in the console
#http://www.codeskulptor.org/#user21_efHoqyHgJRqc7Zc.py


# initialize global variables used in your code
num_range = 100
remaining_guesses = 7

# 1.Decide on a set of global variables that contain 
# the state of the game. For example, one obvious choice
# is the secret number that has been generated by 
# the program. You will need other global variables, 
# especially to accommodate later extensions to the
# basic game.
secretNumber = 0 


#2. Figure out how to generate a random secret 
# number in a given range, low to high
import random


#3. Figure out how to create an input text box 
# using the simplegui module.
import simplegui
# def input_handler(text_input):
#    …
#frame = simplegui.create_frame('Testing', 100, 100)
#inp = frame.add_input('My label', input_handler, 50)


# helper function to start and restart the game
def new_game():
    # 6. Fill in your new_game() function so the generation 
    # of the secret number is now done inside this function.
    print
    print
    print "New Game. Range is from 0 to ", num_range
    print "Number of remaining guesses is ", remaining_guesses
    global secretNumber 
    secretNumber = random.randrange(0, num_range)
    


# define event handlers for control panel
def range100():
    # button that changes range to range [0,100) and restarts
    global num_range, remaining_guesses
    num_range = 100
    remaining_guesses = 7
    new_game()
 

def range1000():
    # button that changes range to range [0,1000) and restarts
    global num_range, remaining_guesses
    num_range = 1000
    remaining_guesses = 10
    new_game()

    
def input_guess(guess):
    # main game logic goes here	
    global remaining_guesses
    remaining_guesses -= 1
    # 4. Write the event handler input_guess(guess) 
    # that takes the input guess, compares it 
    # to the secret number and prints out 
    # the appropriate response
    print
    print "Guess was", guess
    print "Number of remaining guesses is ", remaining_guesses
    number = int(guess)
    if(number == secretNumber):
        print "Correct !" 
    elif(number > secretNumber):
        print "Lower !"
    else:
        print "Higher !"
        
    if (remaining_guesses == 0):
        print "You ran out of guess. The number was ", secretNumber
        # here will call newgame() via range100() or range1000() functions
        # to reinitialize properly variables depending of ranges 100 or 1000
        if (num_range==100):
            range100()
        else:
            range1000()
         
        
# create frame

frame = simplegui.create_frame('Guess the number Game', 200, 200)

# register event handlers for control elements
button1 = frame.add_button('Range: 0 - 100', range100, 200)
button2 = frame.add_button('Range: 0 - 1000', range1000, 200)
inp = frame.add_input('Enter a guess :', input_guess, 200)


# call new_game and start frame
new_game()


# always remember to check your completed program against the grading rubric

